---
- hosts: localhost
  connection: local
  sudo: true

  roles:
    - zzet.rbenv

  vars:
    - rbenv:
        env: user
        version: v0.4.0
        ruby_version: 2.1.2

    - rbenv_users:
        - { name: "klynch", home: "/home/klynch/" }
